package com.mobdeve.s18.roman.isaacnathan.alleymate.data.model

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

// Database table for representing an individual expense associated with a specific event
@Entity(
    tableName = "event_expenses",
    foreignKeys = [
        ForeignKey(
            entity = Event::class,
            parentColumns = ["eventId"],
            childColumns = ["eventId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index(value = ["eventId"])]
)
data class EventExpense(

    // Unique identifier for the expense (auto-generated by Room)
    @PrimaryKey(autoGenerate = true)
    val expenseId: Int = 0,

    // Reference to the associated event
    val eventId: Int,

    // Short description of the expense (e.g., "Booth Rental", "Marketing")
    val description: String,

    // Cost of the expense in cents to avoid floating point precision issues
    val amountInCents: Long
)
